export const NEARBY_AIRPORT_DISCOVERY_CONFIG = Object.freeze({
  radiusNm: 80,
  limit: 5,
});

export const AIRPORT_DISCOVERY_TOPICS = Object.freeze([
  {
    id: "spotter-favorites",
    titleKey: "search.discovery.spotterFavorites.title",
    descriptionKey: "search.discovery.spotterFavorites.description",
    airports: [
      {
        icao: "KBOS",
        iata: "BOS",
        name: "Boston Logan International Airport",
        city: "Boston",
        country: "US",
        lat: 42.36197,
        lon: -71.0079,
        type: "large_airport",
        type_label: "Large Airport",
        discoveryLabelKey: "search.discovery.airportLabels.harborApproaches",
      },
      {
        icao: "KSFO",
        iata: "SFO",
        name: "San Francisco International Airport",
        city: "San Francisco",
        country: "US",
        lat: 37.618999,
        lon: -122.375,
        type: "large_airport",
        type_label: "Large Airport",
        discoveryLabelKey: "search.discovery.airportLabels.parallelArrivals",
      },
      {
        icao: "EHAM",
        iata: "AMS",
        name: "Amsterdam Airport Schiphol",
        city: "Amsterdam",
        country: "NL",
        lat: 52.308613,
        lon: 4.763889,
        type: "large_airport",
        type_label: "Large Airport",
        discoveryLabelKey: "search.discovery.airportLabels.terraceTraffic",
      },
    ],
  },
  {
    id: "major-international-hubs",
    titleKey: "search.discovery.majorInternationalHubs.title",
    descriptionKey: "search.discovery.majorInternationalHubs.description",
    airports: [
      {
        icao: "KJFK",
        iata: "JFK",
        name: "John F. Kennedy International Airport",
        city: "New York",
        country: "US",
        lat: 40.639447,
        lon: -73.779317,
        type: "large_airport",
        type_label: "Large Airport",
        discoveryLabelKey: "search.discovery.airportLabels.transatlanticGate",
      },
      {
        icao: "EGLL",
        iata: "LHR",
        name: "London Heathrow Airport",
        city: "London",
        country: "GB",
        lat: 51.470748,
        lon: -0.459909,
        type: "large_airport",
        type_label: "Large Airport",
        discoveryLabelKey: "search.discovery.airportLabels.globalBanks",
      },
      {
        icao: "VHHH",
        iata: "HKG",
        name: "Hong Kong International Airport",
        city: "Hong Kong",
        country: "HK",
        lat: 22.31184,
        lon: 113.914862,
        type: "large_airport",
        type_label: "Large Airport",
        discoveryLabelKey: "search.discovery.airportLabels.asiaPacificHub",
      },
      {
        icao: "KATL",
        iata: "ATL",
        name: "Hartsfield-Jackson Atlanta International Airport",
        city: "Atlanta",
        country: "US",
        lat: 33.6367,
        lon: -84.428101,
        type: "large_airport",
        type_label: "Large Airport",
        discoveryLabelKey: "search.discovery.airportLabels.southeastMegahub",
      },
      {
        icao: "KORD",
        iata: "ORD",
        name: "Chicago O'Hare International Airport",
        city: "Chicago",
        country: "US",
        lat: 41.9786,
        lon: -87.9048,
        type: "large_airport",
        type_label: "Large Airport",
        discoveryLabelKey: "search.discovery.airportLabels.midcontinentHub",
      },
    ],
  },
  {
    id: "world-of-airports",
    titleKey: "search.discovery.worldOfAirports.title",
    descriptionKey: "search.discovery.worldOfAirports.description",
    airports: [
      {
        icao: "KIAD",
        iata: "IAD",
        name: "Washington Dulles International Airport",
        city: "Washington",
        country: "US",
        lat: 38.9445,
        lon: -77.455803,
        type: "large_airport",
        type_label: "Large Airport",
        discoveryLabelKey: "search.discovery.airportLabels.capitalLongHaul",
      },
      {
        icao: "SCEL",
        iata: "SCL",
        name: "Arturo Merino Benitez International Airport",
        city: "Santiago",
        country: "CL",
        lat: -33.393,
        lon: -70.785797,
        type: "large_airport",
        type_label: "Large Airport",
        discoveryLabelKey: "search.discovery.airportLabels.andesGateway",
      },
      {
        icao: "VTBS",
        iata: "BKK",
        name: "Suvarnabhumi Airport",
        city: "Bangkok",
        country: "TH",
        lat: 13.681108,
        lon: 100.747284,
        type: "large_airport",
        type_label: "Large Airport",
        discoveryLabelKey: "search.discovery.airportLabels.southeastAsiaHub",
      },
    ],
  },
  {
    id: "cargo-hubs",
    titleKey: "search.discovery.cargoHubs.title",
    descriptionKey: "search.discovery.cargoHubs.description",
    airports: [
      {
        icao: "KMEM",
        iata: "MEM",
        name: "Memphis International Airport",
        city: "Memphis",
        country: "US",
        lat: 35.0424,
        lon: -89.9767,
        type: "large_airport",
        type_label: "Large Airport",
        discoveryLabelKey: "search.discovery.airportLabels.integratorHub",
      },
      {
        icao: "PANC",
        iata: "ANC",
        name: "Ted Stevens Anchorage International Airport",
        city: "Anchorage",
        country: "US",
        lat: 61.1744,
        lon: -149.996,
        type: "large_airport",
        type_label: "Large Airport",
        discoveryLabelKey: "search.discovery.airportLabels.polarCargo",
      },
      {
        icao: "KSDF",
        iata: "SDF",
        name: "Louisville Muhammad Ali International Airport",
        city: "Louisville",
        country: "US",
        lat: 38.1744,
        lon: -85.736,
        type: "large_airport",
        type_label: "Large Airport",
        discoveryLabelKey: "search.discovery.airportLabels.nightSort",
      },
    ],
  },
]);
