export const AIRPORT_SEARCH_CONFIG = {
  country: "",
  kind: "all",
  limit: 12,
  debounceMs: 220,
};

// Curated mix of high-traffic hubs across regions. Coordinates and naming come
// from the OurAirports import so these match what `/api/search` returns.
export const FEATURED_AIRPORTS = [
  {
    icao: "KJFK",
    iata: "JFK",
    name: "John F. Kennedy International Airport",
    city: "New York",
    country: "US",
    lat: 40.639447,
    lon: -73.779317,
    type: "large_airport",
    type_label: "Large Airport",
  },
  {
    icao: "KLAX",
    iata: "LAX",
    name: "Los Angeles International Airport",
    city: "Los Angeles",
    country: "US",
    lat: 33.942501,
    lon: -118.407997,
    type: "large_airport",
    type_label: "Large Airport",
  },
  {
    icao: "KORD",
    iata: "ORD",
    name: "Chicago O'Hare International Airport",
    city: "Chicago",
    country: "US",
    lat: 41.9786,
    lon: -87.9048,
    type: "large_airport",
    type_label: "Large Airport",
  },
  {
    icao: "KATL",
    iata: "ATL",
    name: "Hartsfield-Jackson Atlanta International Airport",
    city: "Atlanta",
    country: "US",
    lat: 33.6367,
    lon: -84.428101,
    type: "large_airport",
    type_label: "Large Airport",
  },
  {
    icao: "EGLL",
    iata: "LHR",
    name: "London Heathrow Airport",
    city: "London",
    country: "GB",
    lat: 51.470748,
    lon: -0.459909,
    type: "large_airport",
    type_label: "Large Airport",
  },
  {
    icao: "LFPG",
    iata: "CDG",
    name: "Paris Charles de Gaulle Airport",
    city: "Paris",
    country: "FR",
    lat: 49.00896,
    lon: 2.554117,
    type: "large_airport",
    type_label: "Large Airport",
  },
  {
    icao: "RJTT",
    iata: "HND",
    name: "Tokyo Haneda International Airport",
    city: "Tokyo",
    country: "JP",
    lat: 35.549678,
    lon: 139.786958,
    type: "large_airport",
    type_label: "Large Airport",
  },
  {
    icao: "VHHH",
    iata: "HKG",
    name: "Hong Kong International Airport",
    city: "Hong Kong",
    country: "HK",
    lat: 22.31184,
    lon: 113.914862,
    type: "large_airport",
    type_label: "Large Airport",
  },
  {
    icao: "OMDB",
    iata: "DXB",
    name: "Dubai International Airport",
    city: "Dubai",
    country: "AE",
    lat: 25.24979,
    lon: 55.370992,
    type: "large_airport",
    type_label: "Large Airport",
  },
  {
    icao: "CYYZ",
    iata: "YYZ",
    name: "Toronto Pearson International Airport",
    city: "Toronto",
    country: "CA",
    lat: 43.675935,
    lon: -79.629421,
    type: "large_airport",
    type_label: "Large Airport",
  },
];
