export const MECHANISM_ITEMS = [
  {
    id: "realtimeBackbone",
    groupKey: "mechanism.groups.architecture",
    titleKey: "mechanism.items.realtimeBackbone.title",
    bodyKey: "mechanism.items.realtimeBackbone.body",
    signalKey: "mechanism.items.realtimeBackbone.signal",
    detailKeys: [
      "mechanism.items.realtimeBackbone.details.connect",
      "mechanism.items.realtimeBackbone.details.share",
      "mechanism.items.realtimeBackbone.details.resume",
    ],
    flowKeys: [
      "mechanism.items.realtimeBackbone.flow.browser",
      "mechanism.items.realtimeBackbone.flow.socket",
      "mechanism.items.realtimeBackbone.flow.scheduler",
      "mechanism.items.realtimeBackbone.flow.payload",
    ],
  },
  {
    id: "parallelPipelines",
    groupKey: "mechanism.groups.architecture",
    titleKey: "mechanism.items.parallelPipelines.title",
    bodyKey: "mechanism.items.parallelPipelines.body",
    signalKey: "mechanism.items.parallelPipelines.signal",
    detailKeys: [
      "mechanism.items.parallelPipelines.details.independent",
      "mechanism.items.parallelPipelines.details.batch",
      "mechanism.items.parallelPipelines.details.boundary",
    ],
    flowKeys: [
      "mechanism.items.parallelPipelines.flow.positions",
      "mechanism.items.parallelPipelines.flow.routes",
      "mechanism.items.parallelPipelines.flow.context",
      "mechanism.items.parallelPipelines.flow.ui",
    ],
  },
  {
    id: "trackingTargets",
    groupKey: "mechanism.groups.mechanisms",
    titleKey: "mechanism.items.trackingTargets.title",
    bodyKey: "mechanism.items.trackingTargets.body",
    signalKey: "mechanism.items.trackingTargets.signal",
    detailKeys: [
      "mechanism.items.trackingTargets.details.aircraft",
      "mechanism.items.trackingTargets.details.airport",
      "mechanism.items.trackingTargets.details.fit",
    ],
    flowKeys: [
      "mechanism.items.trackingTargets.flow.select",
      "mechanism.items.trackingTargets.flow.anchor",
      "mechanism.items.trackingTargets.flow.context",
      "mechanism.items.trackingTargets.flow.render",
    ],
  },
  {
    id: "hereMode",
    groupKey: "mechanism.groups.mechanisms",
    titleKey: "mechanism.items.hereMode.title",
    bodyKey: "mechanism.items.hereMode.body",
    signalKey: "mechanism.items.hereMode.signal",
    detailKeys: [
      "mechanism.items.hereMode.details.device",
      "mechanism.items.hereMode.details.sidebar",
      "mechanism.items.hereMode.details.status",
    ],
    flowKeys: [
      "mechanism.items.hereMode.flow.device",
      "mechanism.items.hereMode.flow.map",
      "mechanism.items.hereMode.flow.sidebar",
      "mechanism.items.hereMode.flow.status",
    ],
  },
  {
    id: "nearbyListRendering",
    groupKey: "mechanism.groups.mechanisms",
    titleKey: "mechanism.items.nearbyListRendering.title",
    bodyKey: "mechanism.items.nearbyListRendering.body",
    signalKey: "mechanism.items.nearbyListRendering.signal",
    detailKeys: [
      "mechanism.items.nearbyListRendering.details.distance",
      "mechanism.items.nearbyListRendering.details.virtual",
      "mechanism.items.nearbyListRendering.details.motion",
    ],
    flowKeys: [
      "mechanism.items.nearbyListRendering.flow.payload",
      "mechanism.items.nearbyListRendering.flow.derive",
      "mechanism.items.nearbyListRendering.flow.memo",
      "mechanism.items.nearbyListRendering.flow.paint",
    ],
  },
  {
    id: "canvasAircraftRendering",
    groupKey: "mechanism.groups.mechanisms",
    titleKey: "mechanism.items.canvasAircraftRendering.title",
    bodyKey: "mechanism.items.canvasAircraftRendering.body",
    signalKey: "mechanism.items.canvasAircraftRendering.signal",
    detailKeys: [
      "mechanism.items.canvasAircraftRendering.details.singleLayer",
      "mechanism.items.canvasAircraftRendering.details.projection",
      "mechanism.items.canvasAircraftRendering.details.throttle",
    ],
    flowKeys: [
      "mechanism.items.canvasAircraftRendering.flow.motion",
      "mechanism.items.canvasAircraftRendering.flow.project",
      "mechanism.items.canvasAircraftRendering.flow.sprite",
      "mechanism.items.canvasAircraftRendering.flow.paint",
    ],
  },
  {
    id: "flightTrackingLifecycle",
    groupKey: "mechanism.groups.mechanisms",
    titleKey: "mechanism.items.flightTrackingLifecycle.title",
    bodyKey: "mechanism.items.flightTrackingLifecycle.body",
    signalKey: "mechanism.items.flightTrackingLifecycle.signal",
    detailKeys: [
      "mechanism.items.flightTrackingLifecycle.details.reload",
      "mechanism.items.flightTrackingLifecycle.details.states",
      "mechanism.items.flightTrackingLifecycle.details.trace",
    ],
    flowKeys: [
      "mechanism.items.flightTrackingLifecycle.flow.open",
      "mechanism.items.flightTrackingLifecycle.flow.reload",
      "mechanism.items.flightTrackingLifecycle.flow.acquire",
      "mechanism.items.flightTrackingLifecycle.flow.resolve",
    ],
  },
] as const;
