export const MECHANISM_ITEMS = [
  {
    id: "realtimeBackbone",
    groupKey: "mechanism.groups.architecture",
    titleKey: "mechanism.items.realtimeBackbone.title",
    bodyKey: "mechanism.items.realtimeBackbone.body",
    signalKey: "mechanism.items.realtimeBackbone.signal",
    detailKeys: [
      "mechanism.items.realtimeBackbone.details.connect",
      "mechanism.items.realtimeBackbone.details.share",
      "mechanism.items.realtimeBackbone.details.resume",
    ],
    flowKeys: [
      "mechanism.items.realtimeBackbone.flow.browser",
      "mechanism.items.realtimeBackbone.flow.socket",
      "mechanism.items.realtimeBackbone.flow.scheduler",
      "mechanism.items.realtimeBackbone.flow.providers",
    ],
  },
  {
    id: "positionChannels",
    groupKey: "mechanism.groups.architecture",
    titleKey: "mechanism.items.positionChannels.title",
    bodyKey: "mechanism.items.positionChannels.body",
    signalKey: "mechanism.items.positionChannels.signal",
    detailKeys: [
      "mechanism.items.positionChannels.details.normalize",
      "mechanism.items.positionChannels.details.poll",
      "mechanism.items.positionChannels.details.push",
    ],
    flowKeys: [
      "mechanism.items.positionChannels.flow.view",
      "mechanism.items.positionChannels.flow.channel",
      "mechanism.items.positionChannels.flow.poll",
      "mechanism.items.positionChannels.flow.update",
    ],
  },
  {
    id: "routeQueue",
    groupKey: "mechanism.groups.architecture",
    titleKey: "mechanism.items.routeQueue.title",
    bodyKey: "mechanism.items.routeQueue.body",
    signalKey: "mechanism.items.routeQueue.signal",
    detailKeys: [
      "mechanism.items.routeQueue.details.key",
      "mechanism.items.routeQueue.details.limit",
      "mechanism.items.routeQueue.details.cache",
    ],
    flowKeys: [
      "mechanism.items.routeQueue.flow.callsign",
      "mechanism.items.routeQueue.flow.queue",
      "mechanism.items.routeQueue.flow.cache",
      "mechanism.items.routeQueue.flow.route",
    ],
  },
  {
    id: "postgresBoundary",
    groupKey: "mechanism.groups.architecture",
    titleKey: "mechanism.items.postgresBoundary.title",
    bodyKey: "mechanism.items.postgresBoundary.body",
    signalKey: "mechanism.items.postgresBoundary.signal",
    detailKeys: [
      "mechanism.items.postgresBoundary.details.check",
      "mechanism.items.postgresBoundary.details.persist",
      "mechanism.items.postgresBoundary.details.return",
    ],
  },
  {
    id: "providerFallback",
    groupKey: "mechanism.groups.mechanisms",
    titleKey: "mechanism.items.providerFallback.title",
    bodyKey: "mechanism.items.providerFallback.body",
    signalKey: "mechanism.items.providerFallback.signal",
    detailKeys: [
      "mechanism.items.providerFallback.details.candidates",
      "mechanism.items.providerFallback.details.race",
      "mechanism.items.providerFallback.details.winner",
    ],
  },
  {
    id: "aircraftTrace",
    groupKey: "mechanism.groups.mechanisms",
    titleKey: "mechanism.items.aircraftTrace.title",
    bodyKey: "mechanism.items.aircraftTrace.body",
    signalKey: "mechanism.items.aircraftTrace.signal",
    detailKeys: [
      "mechanism.items.aircraftTrace.details.select",
      "mechanism.items.aircraftTrace.details.append",
      "mechanism.items.aircraftTrace.details.persist",
    ],
  },
  {
    id: "mapOverlays",
    groupKey: "mechanism.groups.mechanisms",
    titleKey: "mechanism.items.mapOverlays.title",
    bodyKey: "mechanism.items.mapOverlays.body",
    signalKey: "mechanism.items.mapOverlays.signal",
    detailKeys: [
      "mechanism.items.mapOverlays.details.layers",
      "mechanism.items.mapOverlays.details.project",
      "mechanism.items.mapOverlays.details.label",
    ],
  },
] as const;
