apiVersion: 1

datasources:
  - name: ADSBao Prometheus
    uid: adsbao-prometheus
    type: prometheus
    access: proxy
    url: ${PROMETHEUS_URL}
    isDefault: true
    basicAuth: true
    basicAuthUser: ${PROMETHEUS_BASIC_AUTH_USER}
    secureJsonData:
      basicAuthPassword: ${PROMETHEUS_BASIC_AUTH_PASSWORD}
    jsonData:
      httpMethod: POST
      timeInterval: 15s
    editable: true
