import { promises as fs } from "node:fs";
import { basename, join } from "node:path";

const ROOT = process.cwd();
const ICON_DIR = join(ROOT, "public", "icons", "aircraft");
const OUT_FILE = join(
  ROOT,
  "src",
  "features",
  "aircraft",
  "icons",
  "aircraftIconAnchors.generated.ts",
);

type AnchorPoint = {
  x: number;
  y: number;
  confidence: "high" | "medium" | "low";
  source: "svg-bounds" | "type-rule";
};

type AnchorRecord = {
  viewBox: [number, number, number, number];
  family: "jet" | "propeller" | "rotorcraft" | "balloon" | "unknown";
  anchors: Record<string, AnchorPoint>;
};

const ROTORCRAFT = new Set([
  "as32",
  "as65",
  "ec20",
  "ec35",
  "ec45",
  "gazl",
  "h47",
  "h60",
  "h64",
  "lynx",
  "mi24",
  "nh90",
  "r44",
  "s61",
  "uh1",
]);

const PROPELLER = new Set([
  "a400",
  "an12",
  "an26",
  "at45",
  "at75",
  "b190",
  "bn2p",
  "c130",
  "c160",
  "c172",
  "c208",
  "c295",
  "cn35",
  "d228",
  "d328",
  "da42",
  "dc3",
  "dh8c",
  "dh8d",
  "do27",
  "do28",
  "e300",
  "f406",
  "p1",
  "p180",
  "p28a",
  "p3",
  "pa46",
  "pc12",
  "pc6t",
  "pc9",
  "sc7",
  "sf25",
  "sf34",
  "st75",
]);

const BALLOON = new Set(["ball"]);

const round = (value: number) => Number(value.toFixed(4));

const point = (
  x: number,
  y: number,
  confidence: AnchorPoint["confidence"] = "medium",
  source: AnchorPoint["source"] = "svg-bounds",
): AnchorPoint => ({
  x: round(x),
  y: round(y),
  confidence,
  source,
});

const parseViewBox = (svg: string): [number, number, number, number] => {
  const match = svg.match(/\bviewBox=["']([^"']+)["']/i);
  if (!match) return [0, 0, 24, 24];
  const values = match[1]
    .trim()
    .split(/[\s,]+/)
    .map((item) => Number(item));
  if (values.length !== 4 || values.some((value) => !Number.isFinite(value))) {
    return [0, 0, 24, 24];
  }
  return values as [number, number, number, number];
};

const familyFor = (name: string): AnchorRecord["family"] => {
  if (ROTORCRAFT.has(name)) return "rotorcraft";
  if (PROPELLER.has(name)) return "propeller";
  if (BALLOON.has(name)) return "balloon";
  if (name === "unidentified") return "unknown";
  return "jet";
};

const anchorsFor = (family: AnchorRecord["family"]) => {
  // Lighting anchors available on all powered aircraft.
  // Aircraft faces UP: nose y→0, tail y→1.
  const lightingAnchors: Record<string, AnchorPoint> = {
    topBeacon: point(0.5, 0.22, "medium", "type-rule"),
    bottomBeacon: point(0.5, 0.78, "medium", "type-rule"),
    landingLight: point(0.5, 0.1, "medium", "type-rule"),
    taxiLight: point(0.5, 0.06, "low", "type-rule"),
    logoLight: point(0.5, 0.92, "low", "type-rule"),
  };

  const anchors: Record<string, AnchorPoint> = {
    nose: point(0.5, 0.02, "medium"),
    tail: point(0.5, 0.96, "medium"),
    fuselageCenter: point(0.5, 0.52, "medium"),
    belly: point(0.5, 0.78, "medium", "type-rule"),
    leftWingTip: point(0.04, 0.52, "medium"),
    rightWingTip: point(0.96, 0.52, "medium"),
    noseUnderside: point(0.5, 0.16, "low", "type-rule"),
    tailLight: point(0.5, 0.96, "medium"),
    antiCollisionBeacon: point(0.5, 0.5, "low", "type-rule"),
    contrailLeft: point(0.43, 0.98, "low", "type-rule"),
    contrailRight: point(0.57, 0.98, "low", "type-rule"),
    ...lightingAnchors,
  };

  if (family === "rotorcraft") {
    // Helicopters: beacon often on engine cowling/rotor mast (higher than
    // the generic topBeacon). Bottom beacon stays on the belly.
    return {
      ...anchors,
      topBeacon: point(0.5, 0.18, "medium", "type-rule"),
      rotorHub: point(0.5, 0.5, "medium", "type-rule"),
      rotorLeftTip: point(0.08, 0.5, "low", "type-rule"),
      rotorRightTip: point(0.92, 0.5, "low", "type-rule"),
      tailRotor: point(0.5, 0.95, "low", "type-rule"),
    };
  }

  if (family === "propeller") {
    return {
      ...anchors,
      propeller: point(0.5, 0.03, "low", "type-rule"),
      leftEngine: point(0.35, 0.5, "low", "type-rule"),
      rightEngine: point(0.65, 0.5, "low", "type-rule"),
    };
  }

  if (family === "balloon") {
    // Balloons have no landing/taxi lights or anti-collision beacons.
    // A single strobe is sometimes mounted on the basket.
    return {
      envelopeCenter: point(0.5, 0.38, "low", "type-rule"),
      basketCenter: point(0.5, 0.88, "low", "type-rule"),
      antiCollisionBeacon: point(0.5, 0.84, "low", "type-rule"),
      bottomBeacon: point(0.5, 0.84, "low", "type-rule"),
    };
  }

  return {
    ...anchors,
    leftEngine: point(0.35, 0.57, "low", "type-rule"),
    rightEngine: point(0.65, 0.57, "low", "type-rule"),
  };
};

const serialize = (records: Record<string, AnchorRecord>) => `// Generated by scripts/generate-aircraft-icon-anchors.ts.
// Do not edit individual entries by hand; update the generator rules instead.

export type AircraftIconAnchorPoint = {
  x: number;
  y: number;
  confidence: "high" | "medium" | "low";
  source: "svg-bounds" | "type-rule";
};

export type AircraftIconAnchorRecord = {
  viewBox: [number, number, number, number];
  family: "jet" | "propeller" | "rotorcraft" | "balloon" | "unknown";
  anchors: Record<string, AircraftIconAnchorPoint>;
};

export const AIRCRAFT_ICON_ANCHORS = ${JSON.stringify(records, null, 2)} as const satisfies Record<string, AircraftIconAnchorRecord>;
`;

const run = async () => {
  const files = (await fs.readdir(ICON_DIR))
    .filter((file) => file.endsWith(".svg"))
    .sort();
  const records: Record<string, AnchorRecord> = {};

  for (const file of files) {
    const name = basename(file, ".svg").toLowerCase();
    const svg = await fs.readFile(join(ICON_DIR, file), "utf8");
    const family = familyFor(name);
    records[name] = {
      viewBox: parseViewBox(svg),
      family,
      anchors: anchorsFor(family),
    };
  }

  await fs.writeFile(OUT_FILE, serialize(records));
  console.log(`wrote ${Object.keys(records).length} aircraft icon anchor records`);
};

run().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
